### ISSUE TITLE
Elasticsearch library does not take advantage of openresty

### ISSUE THREAD

**Issue by leafo** [CriztianiX/lapis-elasticsearch#1]
it looks like the elastic search library uses lua socket directly, so it will block the nginx worker when it runs queries. if possible you should look into using openresty's co-socket api to do non-blocking requests to the elastic search server

**Comment by CriztianiX** [comment]
Hey @leafo! Thanks!
Now lapis-elasticsearch is using my fork of elasticsearch-lua.
This fork contains support for resty cosocket.

https://github.com/CriztianiX/elasticsearch-lua/commit/f470d7557bc2ff3ea651de40334e2c768a07e41c
